project:
  type: website
  preview:
    port: 3000
    browser: true
    watch-inputs: true
    navigate: true
  output-dir: docs

website:
  title: 'ReSight - Next Gen ETL'
  sidebar:
    style: "floating"
    contents:
      - text: "Overview"
        href: index.qmd
      - text: "UPSERT Operations"
        href: upsert-ops.qmd

format:
  html:
    mermaid:
      theme: forest
    theme:
      light: flatly
      dark: darkly
    css: styles.css
    toc: true
    toc-location: right
    code-fold: true
    code-summary: "Show code"
    code-tools: true
    code-copy: true
    code-line-numbers: true
    highlight-style: github